Implemented course project
js-tasks-ru/htmlcss-20210610_anatoly-mironov pull request #21
Opened 2021-07-16 13:28 UTC by anatolimironau

Init

2021-07-16 13:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-16 20:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-16 20:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 19:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-18 19:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-19 09:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-20 13:25 UTC, GSemikozov requested changes

2021-07-20 13:25 UTC, GSemikozov commented on 02-dz0/01-semantic-mockup/style.css
> +    display: inline;
а зачем явно задавать inline? если в качестве элемента меню используется ссылка <a> - то она по умолчанию inline. А чтобы добавить отступ между элементами меню - нужно использовать внешний отступ, margin, а не padding-inline-end: 5px;

2021-07-20 13:25 UTC, GSemikozov commented on 03-lection1/01-button/button.scss
> +    @include font(('Roboto', sans-serif), 16px, 19px, 500, white);
цвет лучше закидывать из переменных

2021-07-20 13:25 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.scss
> +        &:focus-visible ~ .checkbox__content {
с поддержкой не очень https://caniuse.com/?search=%3Afocus-visible

2021-07-20 13:25 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.scss
> +        &:checked ~ .toggle__content {
а как меняется расположение control-tick при :checked?

2021-07-20 13:25 UTC, GSemikozov commented on 07-lection5/04-input/input.scss
> +.textbox {
название класса вводит в заблуждение) гораздо более подходящий вариант - .custom-input или .form-group | .form-input

2021-07-20 13:25 UTC, GSemikozov commented on 07-lection5/04-input/input.scss
> +        outline: none;
еще желательно сбраcывать appearance: none

2021-07-20 13:25 UTC, GSemikozov commented on 07-lection5/04-input/input.scss
> +            opacity: .2;
+ pointer-event: none

2021-07-20 13:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +        display: none;
если скрываем через display: none opacity и visibility не нужно

2021-07-20 13:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +.menu-control-button {
может .toggle-menu-btn?
кроме. того - здесь кнопка реализована как отдельный блок, поэтому желательно ее и вынести в отдельный файл

2021-07-20 13:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +    top: 16px;
внешнее расположение кнопкии должно определяться контекстом (через микс) - в нашем случае это хедер - .header__toggle-menu

2021-07-20 13:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +            .burger-menu__container {
не обязательно создавать дополнительную вложенность и описывать .burger-menu__container внутри &--template

2021-07-20 13:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +    &__color-switch {
theme-switch?

2021-07-20 13:25 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.scss
> +        .toggle {
блок .toggle нужно определить в отдельном месте, либо описывать как элемент текущего блока

2025-11-28 08:29 UTC, closed without merging