04-lection2 - 01-histogram
js-tasks-ru/htmlcss-20210610_anatoly-mironov pull request #7
Opened 2021-06-28 15:52 UTC by anatolimironau

Implemented task 04-lection2 - 01-histogram

2021-06-28 15:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-28 16:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-28 21:35 UTC, GSemikozov requested changes

2021-06-28 21:35 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
здесь это свойство будет лишним (представим что у нас всего 2 колонки - тогда одна будет слева а другая - аж в противоположном конце =))

2021-06-28 21:35 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
здесь, пожалуй, ширину нет смысла задавать через width, можно разве что через flex-basis - на случай, опять же, если в чарте будет мало колонок, или вообще одна (тогда, скажем, flex-basis: 10% сделает ширину колонки в 10%, вместо 9px при width: 9px)

2021-06-29 11:43 UTC, anatolimironau commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
fixed

2021-06-29 11:47 UTC, anatolimironau commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
fixed

2021-06-29 12:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-29 12:32 UTC, GSemikozov approved these changes

2021-06-29 12:32 UTC, merged